name: Deploy Test Net

  push:
    branches:
      - "*"

  pull_request:
    branches:
      - main

jobs:

  network-deploy:
    runs-on: [Bootstrap]
    if: "!contains(github.event.head_commit.message, '{{no-op}}')"
    timeout-minutes: 200
    strategy:
      fail-fast: true
      max-parallel: 4
    steps:
      - name: Set Upstream Variables
        id: set_branch
        shell: bash
        run: |
            echo "::set-output name=pull_branch_name::${GITHUB_REF##*/}"
            echo "::set-output name=instance_name_tag::${GITHUB_REF##*/}-testnet"
            echo "::set-output name=event_type::${{ github.event_name }}"

      - name: Invoke Chia Net Deploy
        run: |
          curl -XPOST -H "Authorization: token ${{ secrets.REPO_ADMIN }}" -H "Accept: application/vnd.github.v3+json" -H "Content-Type: application/json" https://api.github.com/repos/Chia-Network/chia-net-deploy/actions/workflows/chia-introducer.yml/dispatches --data '{"ref": "master", "inputs": { "event_type": "${{ github.event_name }}" , "upstream_branch": "${{ steps.set_branch.outputs.pull_branch_name }}", "instance_name_tag": "${{ steps.set_branch.outputs.instance_name_tag }}" } }'
